- hosts: webservers
  become: yes
  vars:
    http_port: 80 # change to 8000 and proxy is implemented
    https_port: 443 # change to 4443 when proxy is implemented
  roles:
    - apache2
    - nodejs

    
